This patch comes from upstream: http://bugs.python.org/issue24299

--- Python-2.7.10/Lib/test/test__locale.py	Tue May 26 01:35:54 2015 -0700
+++ Python-2.7.10/Lib/test/test__locale.py	Wed May 27 21:23:02 2015 +0300
@@ -23,7 +23,8 @@ candidate_locales = ['es_UY', 'fr_FR', '
     'de_DE', 'sr_YU', 'br_FR', 'nl_BE', 'sv_FI', 'pl_PL', 'fr_CA', 'fo_FO',
     'bs_BA', 'fr_LU', 'kl_GL', 'fa_IR', 'de_BE', 'sv_SE', 'it_CH', 'uk_UA',
     'eu_ES', 'vi_VN', 'af_ZA', 'nb_NO', 'en_DK', 'tg_TJ', 'ps_AF.UTF-8', 'en_US',
-    'es_ES.ISO8859-1', 'fr_FR.ISO8859-15', 'ru_RU.KOI8-R', 'ko_KR.eucKR']
+    'fr_FR.ISO8859-1', 'fr_FR.UTF-8', 'fr_FR.ISO8859-15@euro',
+    'ru_RU.KOI8-R', 'ko_KR.eucKR']
 
 # Workaround for MSVC6(debug) crash bug
 if "MSC v.1200" in sys.version:
@@ -37,8 +38,8 @@ if "MSC v.1200" in sys.version:
 # value is not known, use '' .
 known_numerics = {
     'en_US': ('.', ','),
-    'fr_FR' : (',', ' '),
     'de_DE' : (',', '.'),
+    'fr_FR.UTF-8' : (',', ' '),
     'ps_AF.UTF-8' : ('\xd9\xab', '\xd9\xac'),
 }
 
